Repository mk2e/market-everyone, pull requests merged in 2021-12, with the labels that each got.

#13 feat: 통계 차트 구현
  module-web/src/main/resources/static/vendor/jquery/chart/chart.js
  module-web/src/main/resources/templates/itemInsert.html
  module-web/src/main/resources/templates/itemList.html
  module-web/src/main/resources/templates/staticList.html
  module-web/src/main/resources/templates/statics.html
  module-web/src/main/resources/templates/test.html
Labels: front

#16 feat/login 관리자 로그인 기능 구현
  module-admin/src/main/java/admin/HomeController.java
  module-admin/src/main/java/admin/config/WebSecurityConfig.java
  module-admin/src/main/java/admin/login/controller/LoginController.java
  module-admin/src/main/resources/application.yml
  module-admin/src/main/resources/templates/login/login.html
Labels: backend, front

#18 chore: module-web, module-admin 로컬 도커DB와 연동하기 위한 설정 구성
  build.gradle
  module-admin/src/main/resources/application.yml
  module-web/src/main/java/web/order/controller/OrderController.java
  module-web/src/main/resources/application.yml
Labels: bug, backend

#21 feat: 고객센터 화면 구현 및 ServiceCenterController 추가
  module-web/src/main/java/web/ServiceCenterController.java
  module-web/src/main/resources/templates/layout/sc-base.html
  module-web/src/main/resources/templates/layout/sc-sidebar.html
  module-web/src/main/resources/templates/service/faq.html
  module-web/src/main/resources/templates/service/my-qna.html
  module-web/src/main/resources/templates/service/notice.html
  module-web/src/main/resources/templates/service/personal-qna-form.html
  module-web/src/main/resources/templates/service/seller-register-form.html
Labels: front

#27 chore: JPA 네이밍 전략을 lowerCarmelCase -> UPPER_SNAKE_CASE로 변경
  module-web/src/main/java/web/common/strategy/UpperCaseNamingStrategy.java
  module-web/src/main/resources/application.yml
Labels: chore, backend

#31 fix/setting: Gradle 멀티모듈 side-effect 수정
  module-admin/src/main/java/admin/AdminApplication.java
  module-admin/src/main/resources/application.yml
Labels: bug

#32 Feat/member User 기능 구현
  build.gradle
  module-web/src/main/java/web/ErrorController.java
  module-web/src/main/java/web/HomeController.java
  module-web/src/main/java/web/ListController.java
  module-web/src/main/java/web/LoginController.java
  module-web/src/main/java/web/common/AuthConverter.java
  module-web/src/main/java/web/common/Utils.java
  module-web/src/main/java/web/configuration/WebSecurityConfig.java
  module-web/src/main/java/web/exception/ApplicationException.java
  module-web/src/main/java/web/exception/auth/UnsupportedOauthVendorException.java
  module-web/src/main/java/web/member/controller/MemberController.java
  module-web/src/main/java/web/member/controller/dto/request/MemberRequest.java
  module-web/src/main/java/web/member/controller/dto/response/MemberResponse.java
  module-web/src/main/java/web/member/domain/Member.java
  module-web/src/main/java/web/member/domain/MemberRepository.java
  module-web/src/main/java/web/member/service/MemberService.java
  module-web/src/main/java/web/security/AuthenticateUser.java
  module-web/src/main/java/web/security/CustomAccessDeniedHandler.java
  module-web/src/main/java/web/security/CustomAuthenticationEntryPoint.java
  module-web/src/main/java/web/security/CustomAuthenticationFilter.java
  module-web/src/main/java/web/security/CustomLogoutFilter.java
  module-web/src/main/java/web/security/UserPrincipal.java
  module-web/src/main/java/web/security/UserPrincipalService.java
  module-web/src/main/java/web/security/oauth2/CustomAuthenticationFailureHandler.java
  module-web/src/main/java/web/security/oauth2/CustomAuthenticationSuccessHandler.java
  module-web/src/main/java/web/security/oauth2/Oauth2UserPrincipalService.java
  module-web/src/main/java/web/security/oauth2/provider/GoogleUserInfo.java
  module-web/src/main/java/web/security/oauth2/provider/OAuth2UserInfo.java
  module-web/src/main/java/web/security/oauth2/util/CookieUtils.java
  module-web/src/main/java/web/user/controller/UserController.java
  module-web/src/main/java/web/user/controller/UserRestController.java
  module-web/src/main/java/web/user/controller/dto/request/UserInfoUpdateRequest.java
  module-web/src/main/java/web/user/controller/dto/request/UserSignUpRequest.java
  module-web/src/main/java/web/user/controller/dto/response/UserInfoResponse.java
  module-web/src/main/java/web/user/domain/Address.java
  module-web/src/main/java/web/user/domain/Role.java
  module-web/src/main/java/web/user/domain/User.java
  module-web/src/main/java/web/user/domain/UserRepository.java
  module-web/src/main/java/web/user/service/UserService.java
  module-web/src/main/resources/application.yml
  module-web/src/main/resources/static/images/google-logo.png
  module-web/src/main/resources/templates/admin.html
  module-web/src/main/resources/templates/error/unauthorized.html
  module-web/src/main/resources/templates/home.html
  module-web/src/main/resources/templates/layout/auth/base.html
  module-web/src/main/resources/templates/layout/home/base.html
  module-web/src/main/resources/templates/layout/navigation.html
  module-web/src/main/resources/templates/layout/user/base.html
  module-web/src/main/resources/templates/layout/user/sidebar.html
  module-web/src/main/resources/templates/order/orderList.html
  module-web/src/main/resources/templates/user/join.html
  module-web/src/main/resources/templates/user/login.html
  module-web/src/main/resources/templates/user/myInfo.html
  module-web/src/main/resources/templates/user/myReviewList.html
Labels: backend, front

#35 feat: 판매자 목록 출력기능 구현
  .gitignore
  build.gradle
  module-admin/src/main/java/admin/AdminApplication.java
  module-admin/src/main/java/admin/common/dto/PageRequestDTO.java
  module-admin/src/main/java/admin/common/dto/PageResultDTO.java
  module-admin/src/main/java/admin/config/QuerydslConfig.java
  module-admin/src/main/java/admin/config/WebSecurityConfig.java
  module-admin/src/main/java/admin/login/controller/LoginController.java
  module-admin/src/main/java/admin/security/handler/FormAuthenticationFailureHandler.java
  module-admin/src/main/java/admin/security/provider/FormAuthenticationProvider.java
  module-admin/src/main/java/admin/security/service/UserDetails.java
  module-admin/src/main/java/admin/security/service/UserDetailsService.java
  module-admin/src/main/java/admin/seller/controller/SellerController.java
  module-admin/src/main/java/admin/seller/controller/dto/SellerDTO.java
  module-admin/src/main/java/admin/seller/service/SellerService.java
  module-admin/src/main/java/admin/seller/service/SellerServiceImpl.java
  module-admin/src/main/resources/application-dev.yml
  module-admin/src/main/resources/application.yml
  module-admin/src/main/resources/templates/layout/sidebar.html
  module-admin/src/main/resources/templates/layout/topbar.html
  module-admin/src/main/resources/templates/login/denied.html
  module-admin/src/main/resources/templates/login/login.html
  module-admin/src/main/resources/templates/seller/list.html
  module-web/src/main/java/web/WebApplication.java
  module-web/src/main/java/web/common/entity/BaseEntity.java
  module-web/src/main/java/web/configuration/QuerydslConfig.java
  module-web/src/main/java/web/notice/controller/NoticeController.java
  module-web/src/main/java/web/seller/domain/Seller.java
  module-web/src/main/java/web/seller/domain/SellerRepository.java
  module-web/src/main/java/web/seller/domain/SellerRepositoryCustom.java
  module-web/src/main/java/web/seller/domain/SellerRepositoryImpl.java
  module-web/src/main/java/web/seller/domain/SellerStatus.java
Labels: backend, front

#36 feat: admin 판매자 관리 기능 구현
  module-admin/src/main/java/admin/seller/controller/SellerController.java
  module-admin/src/main/java/admin/seller/controller/dto/SellerDTO.java
  module-admin/src/main/java/admin/seller/controller/dto/SellerRequestDTO.java
  module-admin/src/main/java/admin/seller/controller/dto/SellerResponseDTO.java
  module-admin/src/main/java/admin/seller/service/SellerService.java
  module-admin/src/main/java/admin/seller/service/SellerServiceImpl.java
  module-admin/src/main/resources/templates/seller/list.html
  module-admin/src/test/java/admin/seller/service/SellerServiceTest.java
  module-web/src/main/java/web/common/entity/BaseEntity.java
  module-web/src/main/java/web/seller/domain/Seller.java
Labels: backend, front

#38 feat: 판매자 관리 기능 구현
  module-admin/src/main/java/admin/seller/controller/SellerController.java
  module-admin/src/main/java/admin/seller/controller/dto/SellerResponseDTO.java
  module-admin/src/main/java/admin/seller/service/SellerService.java
  module-admin/src/main/resources/messages.properties
  module-admin/src/main/resources/messages_en.properties
  module-admin/src/main/resources/templates/layout/sidebar.html
  module-admin/src/main/resources/templates/seller/seller.html
  module-admin/src/main/resources/templates/seller/sellers.html
  module-admin/src/main/resources/templates/seller/wait_sellers.html
  module-web/src/main/java/web/seller/domain/Seller.java
  module-web/src/main/java/web/seller/domain/SellerRepositoryCustom.java
  module-web/src/main/java/web/seller/domain/SellerRepositoryImpl.java
Labels: backend

#45 feat: 게시판 불러오기 기능 구현(페이징 QueryDSL 이용)
  module-admin/src/main/java/admin/board/controller/dto/BoardResponseDTO.java
  module-admin/src/main/java/admin/board/service/BoardService.java
  module-admin/src/main/java/admin/seller/controller/dto/SellerResponseDTO.java
  module-admin/src/main/resources/messages.properties
  module-admin/src/main/resources/templates/board/board.html
  module-admin/src/main/resources/templates/layout/sidebar.html
  module-web/src/main/java/web/board/domain/Board.java
  module-web/src/main/java/web/board/domain/BoardRepository.java
  module-web/src/main/java/web/board/domain/BoardRepositoryCustom.java
  module-web/src/main/java/web/board/domain/BoardRepositoryImpl.java
  module-web/src/main/java/web/user/domain/User.java
Labels: backend

#47 feat: 게시글 수정,삭제 화면-기능 구현
  build.gradle
  module-admin/src/main/java/admin/board/controller/BoardController.java
  module-admin/src/main/java/admin/board/controller/dto/BoardRequestDTO.java
  module-admin/src/main/java/admin/board/service/BoardService.java
  module-admin/src/main/resources/messages.properties
  module-admin/src/main/resources/templates/board/add_form.html
  module-admin/src/main/resources/templates/board/board.html
  module-admin/src/main/resources/templates/board/board_list.html
  module-admin/src/main/resources/templates/board/edit_form.html
  module-admin/src/test/java/admin/seller/service/SellerServiceTest.java
  module-web/src/main/java/web/board/domain/Board.java
Labels: backend, front
